# ASP.NET Core (.NET Framework) Pipeline
# This pipeline builds and tests an ASP.NET Core project targeting the full .NET Framework.

trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  # Install NuGet
  - task: NuGetToolInstaller@1

  # Restore NuGet packages
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'

  # Build Solution
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: >
        /p:DeployOnBuild=true 
        /p:WebPublishMethod=Package 
        /p:PackageAsSingleFile=true 
        /p:SkipInvalidConfigurations=true 
        /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)/WebApp.zip" 
        /p:DeployIisAppPath="Default Web Site"
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  # Run Unit Tests
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\*test*.dll'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  # Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
